### ISSUE TITLE
 install No prebuilt binaries found (target=10.15.1 runtime=node arch=x64 platform=linux)

### ISSUE THREAD

**Issue by CarlosFernandoXavier** [nolanlawson/hello-electron-with-pouchdb#13]
Hi! I need to use a pouchdb to continue my project, but when I run the command **npm install pouchdb**, it shows this problem on my screen:

> leveldown@3.0.0 install /home/xavier/Documentos/Projetos react/teste1/node_modules/leveldown
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=10.15.1 runtime=node arch=x64 platform=linux)
make: Entering directory '/home/xavier/Documentos/Projetos react/teste1/node_modules/leveldown/build'
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/builder.o
make: g++: Command not found
deps/leveldb/leveldb.target.mk:154: recipe for target 'Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/builder.o' failed
make: *** [Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/builder.o] Error 127
make: Leaving directory '/home/xavier/Documentos/Projetos react/teste1/node_modules/leveldown/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.15.0-20-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/xavier/Documentos/Projetos react/teste1/node_modules/leveldown
gyp ERR! node -v v10.15.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN ts-pnp@1.0.1 requires a peer of typescript@* but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! leveldown@3.0.0 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the leveldown@3.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/xavier/.npm/_logs/2019-02-24T04_24_44_099Z-debug.log

I know that in Windows 10, the command **npm install -g windows-build-tools** resolve the problem, but as for Linux Mint, is there a similar command?

**Comment by CarlosFernandoXavier** [comment]
I found out the answear in another issue. I just needed run a simple command: **sudo apt-get install python build-essential**

Follow the link of the issue: https://github.com/magento-research/pwa-studio/issues/820

Sorry for the incovenience
