### ISSUE TITLE
sqlite3 doesn't compile for electron

### ISSUE THREAD

**Issue by nolanlawson** [nolanlawson/hello-electron-with-pouchdb#3]
Bug seems to be in sqlite3, but it's affecting us.

```
gyp: Undefined variable module_name in binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\Nolan\workspace\electron-quick-start\node_modules\node-gyp\lib\configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Nolan\\workspace\\electron-quick-start\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=1.3.2" "--arch=x64" "--dist-url=https://atom.io/download/atom-shell"
gyp ERR! cwd C:\Users\Nolan\workspace\electron-quick-start\node_modules\sqlite3
gyp ERR! node -v v6.3.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

```

**Comment by nolanlawson** [comment]
To repro, just try to do the same for `sqlite3` that we're currently doing for `leveldown` in the `poinstall.sh` script.

**Comment by Steviey** [comment]
+1 still pending

**Comment by nolanlawson** [comment]
`Undefined variable module_name in binding.gyp while trying to load binding.gyp`. Incidentally I have run into this multiple times when using sqlite3 (e.g. when trying to get it to run for Tessel) and it seems to be a bug in node-sqlite3 related to their gyp scripts.

**Comment by nolanlawson** [comment]
this is fixed now

**Comment by nolanlawson** [comment]
whopos
